# Generated by Django 5.1.7 on 2025-05-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='loyalty_level',
            field=models.CharField(choices=[('all', 'All'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='all', help_text='Set who can see this code: All users or based on loyalty tier.', max_length=10),
        ),
    ]
